# Copyright (c) 2020 Allan Mobley. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.

trigger:
  tags:
    include:
    - v*

# no PR triggers
pr: none

pool:
  vmImage: 'ubuntu-latest'

steps:

# Specify a particular version of the .NET SDK
- task: UseDotNet@2
  displayName: 'Set SDK'
  inputs:
    packageType: sdk
    version: 3.1.300
    installationPath: $(Agent.ToolsDirectory)/dotnet

# Build samples. Not strictly required to create the package,
# but we want the pipeline to halt if this step fails.
- script: dotnet build --configuration Release
  workingDirectory: samples/BlazorServer
  displayName: Build BlazorServer
- script: dotnet build --configuration Release
  workingDirectory: samples/BlazorWasm
  displayName: Build BlazorWasm

# Create the NuGet package file
- script: dotnet pack --configuration Release
  workingDirectory: src
  displayName: Pack Src

# Upload the NuGet package file to a nuget feed
- task: NuGetCommand@2
  displayName: Push package to feed
  inputs:
    command: 'push'
    packagesToPush: 'src/bin/Release/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'fb9a5fc3-2f2f-4cd6-b9c5-867cc1302618'
    allowPackageConflicts: true